### ISSUE TITLE
Please add how to get refresh token

### ISSUE THREAD

**Issue by chrisrobertsoncypress** [auth0-samples/auth0-WinFormsWPF-oidc-samples#12]
# Issue Report

You have to add
 extraParameters.Add("scope",  "openid offline_access");

before you call LoginAsync or you will get error "id token not contained in result"

Note the "openid" parameter which is not mentioned anywhere in the documentation.

**Comment by frederikprijck** [comment]
Sorry for not getting back to you any sooner, these things are always better reported at https://github.com/auth0/auth0-oidc-client-net, which contains the information and documentation for the SDK, beyond just the sample.

However, that doesn't justify the silence here, our sincere apologies.

Noted the feedback, and will see to add something to the docs as your feedback is still valid, even 3 years after reporting it.
