### ISSUE TITLE
Application is stuck after calling LoginAsync

### ISSUE THREAD

**Issue by KarlijnsHub** [auth0-samples/auth0-WinFormsWPF-oidc-samples#20]
# Issue Report

### Description

What's going wrong is that the application, WindowsFormSample, is stuck after calling LoginAsync

`var result = await client.LoginAsync();`

It does not give an error or any kind of result. This happens only when I use Visual Studio 2019 as an admin. If I don't use Visual Studio as an admin it works fine. You might expect it to be the otherway around, but a collegue tested it as well and got the same result. 

### Steps to reproduce the problem

I cloned the WindowsFormSample and updated the .Net version to 4.7.2. Then I updated the Nuget Package Auth0.OidcClient.WinForms to version 3.1.2. 

When I downgrade Auth0.OidcClient.WinForms to 2.4.1. it works fine, admin or no admin.

I'd appreciate any help on this.

**Comment by moorer2k** [comment]
On the readme for the OidcClient source,, they have a section talking about breaking changes that are made in v3.  This explains it here, unfortunately.

> v3 of this library targets only .NET Standard 2.0 and drops support for .NET Standard 1.4 and .NET Framework 4.5.2.

Check it out [here](https://github.com/auth0/auth0-oidc-client-net)

**Comment by Maracaipe611** [comment]
@moorer2k this should be setted by default. I had the same problem

**Comment by benwozniak** [comment]
Our team ran into this issue as well. An update to the quickstart would be appreciated, we are new to authentication code so it's frustrating when things do not work out of the box.

**Comment by frederikprijck** [comment]
Sorry for not getting back to this, this must have fallen through the cracks. We have improved the visibility of our sample repositories to avoid this from happening again.

Even though it's been a while, I gave this another try and can not reproduce this anymore, so I assume this has been resolved throughout the time.
