### ISSUE TITLE
Cannot run compiled exe

### ISSUE THREAD

**Issue by GlobeProgger** [auth0-samples/auth0-WinFormsWPF-oidc-samples#23]
### Description

After cloning the repo I opened and build the WPFSample solution successfully. Then I tried to Start a debug session and gett the following error: 
![image](https://user-images.githubusercontent.com/11160586/92137170-2753a480-ee0d-11ea-8f4c-3437d99c8a77.png)

When I try to run the WPFSample.exe manually:
![image](https://user-images.githubusercontent.com/11160586/92137348-50743500-ee0d-11ea-9bf8-d2a5235ae9f1.png)

I have sufficient permissions:
![image](https://user-images.githubusercontent.com/11160586/92137606-97fac100-ee0d-11ea-9cfa-d043f3c9e489.png)

### Steps to reproduce the problem

Clone repo, open in VS 2019, build and press F5

**Comment by frederikprijck** [comment]
Sorry for not getting back to you sooner, I tested this and I can run the application perfectly fine.

Given it's been a while, I am going to close the issue.
