### ISSUE TITLE
AccessToken Invalid Signature

### ISSUE THREAD

**Issue by Chandrankar** [auth0-samples/auth0-WinFormsWPF-oidc-samples#27]
# Issue Report

I need to build a desktop application for existing website made using React frontend and Node Backend.

I need to make Http Request to a Server written in NodeJs but it throws an error 401(Unauthorized) when I try to get Token from the website The accesstoken is different
The AccessToken which I get using the example is showing Invalid Signature when I try to verify it using jwt.io

**Comment by frederikprijck** [comment]
Sorry for not getting back to you. Unsure how this repository relates to react or node.

If you would still have issues, I would encourage to open a new issue with information that does involve the technologies used in this sample.

Also be sure to specify an audience to be sure you get a JWT back from Auth0.
