### ISSUE TITLE
Prefill email field

### ISSUE THREAD

**Issue by tram200** [auth0-samples/auth0-WinFormsWPF-oidc-samples#28]
I am trying to get the Auth0 client to prefill the email field by passing a dictionary to the Task<LoginResult> LoginAsync(object extraParameters = null) according to this https://auth0.com/docs/libraries/lock/lock-configuration#params-object it should be possible, but its unclear how to achieve this within c# wpf.

I have tried using the following as the "extraParameters":

- new Dictionary<string, string>{ {"prefill", "test@test.com" } } 
- new Dictionary<string, string>{ {"email", "test@test.com" } }

But neither have any impact, is there a way to do this?

**Comment by frederikprijck** [comment]
The OIDC parameter for this is login_hint. Can you verify it works as expected if you use login_hint ?

**Comment by tram200** [comment]
yes this works, thank you for the feedback
