### ISSUE TITLE
 NETSDK1135: SupportedOSPlatformVersion 10.0.18362.0 cannot be higher than TargetPlatformVersion 7.0.

### ISSUE THREAD

**Issue by colhountech** [auth0-samples/auth0-WinFormsWPF-oidc-samples#29]
# Issue Report

If you are reporting a bug, please fill the sections below (if they are applicable), otherwise feel free to delete those that don't apply. Thank you! 🙏🏼

### Description

What are you reporting? 

NuGet Package "Auth0.OidcClient.WinForms" Version="3.2.7" does not work.

### Expected behaviour

* Create new .NET Core 6.0 WinForms App
* Add Nuget Package Auth0.Oidc.Client.WinForms
* Builds sucesfully.

### Actual behaviour 

* When you build the .NET Core 6.0 version you, get the build error as soon as you add the nuget package, even before you add any code to empty WinForms .NET Core Project. 
* Works fine with .NET Full Fat Framework 4.8

* Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1135	SupportedOSPlatformVersion 10.0.18362.0 cannot be higher than TargetPlatformVersion 7.0.	WinFormsAppCore6	C:\Program Files\dotnet\sdk\7.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	188	

Tell us what actually happens.

As above.

### Steps to reproduce the problem

Tell us what we should do to reproduce the issue.

As Above.

### Language / Framework Versions

```
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
```

### Testing environment

1. **Operating system:**

OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free

### Screenshots

None.

**Comment by frederikprijck** [comment]
This should be related to https://github.com/auth0/auth0-oidc-client-net/issues/205#issuecomment-873667447, even tho that comment is for .NET5, the idea is the same for .NET6 and 7.
