### ISSUE TITLE
LoginAsync hangs in admin mode

### ISSUE THREAD

**Issue by Suresh3d** [auth0-samples/auth0-WinFormsWPF-oidc-samples#30]
# Issue Report

If you are reporting a bug, please fill the sections below (if they are applicable), otherwise feel free to delete those that don't apply. Thank you! 🙏🏼

### Description
Hi ,
I am using native winform application from here to login to my web page . [Auth0 WPF / Winforms SDK Quickstarts: Login](https://auth0.com/docs/quickstart/native/wpf-winforms).

If I run the application normally everything works fine and I am getting token from my web server. but if I run the application in admin mode , it hangs after this call forever,

await client.LoginAsync(extraParameters: extraParameters).

Can anyone please help me with this.

### Expected behaviour

It should login and return token.

### Actual behaviour 

It hangs forever. 

### Steps to reproduce the problem

Create exe out of winform application with required credentials for login. run the exe in normal mode . It will work fine . Run the exe in admin mode "Run as Administrator" it hangs forever. 

### Language / Framework Versions

1 .Net version 4.6.2

### Testing environment

1. windows 10

**Filling this, you're helping yourself and repo maintainers in solving your issues quicker! Teamwork makes the dreamwork 🤜🏼🤛🏻**

**Comment by frederikprijck** [comment]
Thanks for reaching out and sorry for the late reply. 

There is a thread on community.auth0.com that explains what's happening and how you can work around it, see: https://community.auth0.com/t/howto-use-the-auth0-oidcclient-winforms-sdk-with-edge-chromium-webview2/57746

Let me know if that doesn't work.
