### ISSUE TITLE
Error Loading discovery document: Issuer name is missing

### ISSUE THREAD

**Issue by HarperRussell** [auth0-samples/auth0-WinFormsWPF-oidc-samples#31]
I am receiving the following error when using the Auth0.OidcClient.WinForms assembly (3.2.8) in a ASP.NET Web Application targeting .NET 4.8:

**Error Loading discovery document: Issuer name is missing**

It's a simple implementation of the example code:

private Auth0Client client;

 client = new Auth0Client(new Auth0ClientOptions
            {
                Domain = "{DOMAIN}",
                ClientId = "{CLIENTID}"
            });

await client.LoginAsync(); // this is where it fails

Is this a known issue?  Are there any resolutions?

**Comment by abdala762** [comment]
I had the same issue with Auth0.OidcClient.WPF and I was able to resolve it by using an older version of the NuGet Package (3.2.3)
